#!/usr/bin/env bash
# AminoCloud standardized entrypoint — generated by seed-ac-dirs.sh
# Runtime environment variables (injected by the AC pipeline worker):
#   AC_INPUT_<PORT_ID_UPPER>   path to each declared input file/dir
#   AC_OUTPUT_DIR              write all outputs here
#   AC_CPU_THREADS             allocated vCPU count (integer)
#   AC_MEMORY_GB               allocated memory in GB (integer)
#   AC_JOB_ID                  pipeline job UUID (for log correlation)
#   AC_STEP_ID                 job step UUID (for log correlation)
set -euo pipefail
mkdir -p "${AC_OUTPUT_DIR}"

java -Xmx"${AC_MEMORY_GB}g" -jar /opt/picard/picard.jar MarkDuplicates \
    INPUT="${AC_INPUT_BAM_IN}" \
    OUTPUT="${AC_OUTPUT_DIR}/deduped.bam" \
    METRICS_FILE="${AC_OUTPUT_DIR}/markdup_metrics.txt" \
    REMOVE_DUPLICATES=false \
    CREATE_INDEX=true \
    VALIDATION_STRINGENCY=LENIENT
